compile_latex:
  image: kjarosh/latex:2023.1
  before_script:
    - apk add make
    - apk add git
  script:
    - make clean
    - make --keep-going all || echo "failure"
  artifacts:
    paths:
      - ./build/*.pdf
compile_typst:
  image: ghcr.io/typst/typst:latest
  before_script:
    - apk add make
    - apk add git
    - apk add bash
  script:
    - make typst
  artifacts:
    paths:
      - ./build/*.pdf