compile_pdf:
  image: guusk/docker-latex
  script:
    - make clean all
  artifacts:
    paths:
      - la.pdf
      - stocha.pdf
      - dsal.pdf
      - fosap.pdf
      - bus.pdf
      - mechanik_i.pdf
      - maschinengestaltung_i.pdf
      - numrech.pdf
      - buk.pdf
