stages:
  - build
  - deploy

build:latex:
  stage: build
  image: kjarosh/latex:2023.1
  needs: []
  rules:
    - changes
      - /*.{tex, cls}
      - Makefile
      - scripts/*
  only:
    - master
    - merge_requests
  before_script:
    - apk add make
    - apk add git
  script:
    - make clean
    - make --keep-going all || echo "failure"
  artifacts:
    name: latex-artifacts
    paths:
      - ./build/*.pdf
build:typst:
  stage: build
  image: ghcr.io/typst/typst:latest
  needs: []
  rules:
    - changes
      - /*.typ
      - Makefile
      - scripts/*
  only:
    - master
    - merge_requests
  before_script:
    - apk add make
    - apk add git
    - apk add bash
  script:
    - make typst
  artifacts:
    name: typst-artifacts
    paths:
      - ./build/*.pdf

deploy:
  stage: deploy
  only: 
   - master
  needs:
    - job: build:latex
      optional: true
    - job: build:typst
      optional: true
  image: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
  script: 
    - gcloud --quiet components update

    - echo $GCP_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID

    # clear bucket and then upload files
    - gsutil rm -a $GCP_BUCKET_URL/** 
    - gcloud storage cp --cache-control="public, max-age=3600" metadata.json $GCP_BUCKET_URL
    - gcloud storage cp --cache-control="public, max-age=3600" build/* $GCP_BUCKET_URL