compile_pdf:
  image: guusk/docker-latex:xenial
  script:
    - make clean all
  artifacts:
    paths:
      - la.pdf
      - stocha.pdf
      - dsal.pdf
      - fosap.pdf
      - bus.pdf
      - maschinengestaltung_i.pdf
      - numrech.pdf
      - buk.pdf
      - swt.pdf
      - datkom.pdf
      - malo.pdf
      - dbis.pdf
      - effi.pdf
      - afi.pdf
      - ai.pdf
      - cg.pdf
      - bpi.pdf
      - aat.pdf
      - spa.pdf
